spring.application.name=current-percentage-service

spring.datasource.url=jdbc:postgresql://localhost:5432/energy_community_db
spring.datasource.username=disysuser
spring.datasource.password=disyspw
spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.enabled=false
spring.jpa.hibernate.ddl-auto=validate